import { createClient } from '@supabase/supabase-js'

const supabaseUrl = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cmljbGlleHNweXpkYmxsZ2JzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODAxMzczMywiZXhwIjoyMDkzNTg5NzMzfQ.MzSBmxHdB5xV0dglIr3zzJuEwjSc7yVDRr2WRQaOvgo"
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cmljbGlleHNweXpkYmxsZ2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMTM3MzMsImV4cCI6MjA5MzU4OTczM30.tfE0Ompouqxg0l_pam7XDnCSh_K-WusVkV2jEd2yD6Qss"

export const supabase = createClient(supabaseUrl, supabaseAnonKey)